language: node_js
node_js:
    - "0.8"
before_script: 
    - npm install -g bower
    - bower cache clean
    - bower install
script: grunt test --force
branches:
  only:
    - master
    - develop
    - website
